FROM node:17 as build
WORKDIR /usr/app/client
COPY . /usr/app/client
COPY .env /usr/app/client/.env
RUN npm ci 
RUN npm run build

FROM nginx:1.23.1-alpine
EXPOSE 80
COPY ./docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/client/dist /usr/share/nginx/html