services:
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes: 
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env

  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "4000:4000"
    volumes: 
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    environment: 
      POSTGRES_PASSWORD: calculator_user_password
      POSTGRES_HOST: postgres
    command: sh -c 'echo "Running migrations..." && npx knex migrate:latest --knexfile /app/src/database/options/postgres/knexfile.ts && echo "Migrations complete." && npm run dev'

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres
    ports:
      - 5433:5432
    volumes: 
      - 'postgresdb-data:/var/lib/postgresql/data'
      - ./server/src/database/options/postgres/init-script.sql:/docker-entrypoint-initdb.d/create-tables.sql
    depends_on:
      - server
    
volumes:
  mongodb-data:
  postgresdb-data: