services:
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes: 
      - ./client:/app
      - /app/node_modules

  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "4000:4000"
    volumes: 
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - ./server/src/database/options/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  postgres:
    image: postgres
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: pa55word_to_postgre5Ql
    volumes: 
      - 'postgresdb-data:/var/lib/postgresql/data'
      - ./server/src/database/options/postgres/init-script.sql:/docker-entrypoint-initdb.d/create-tables.sql

volumes:
  mongodb-data:
  postgresdb-data: