export const calculatorViewConstants = {
  MIN_BUTTON_VALUE: 1,
  MAX_BUTTON_VALUE: 9,
  NUMBERS_COLUMNS_AMOUNT: 3,
  THRESHOLD_ROW_LEVEL: 6,
  NUMBERS_AMOUNT: 10,
  BUTTON_WIDTH: 102,
  BUTTON_MIN_WIDTH: 70,
};
